// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivitiesTabsController from "./activities_tabs_controller"
application.register("activities-tabs", ActivitiesTabsController)

import ActivityDropdownController from "./activity_dropdown_controller"
application.register("activity-dropdown", ActivityDropdownController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
